# Azure SQL Database Configuration
db.server=myfreesqldbserver-sc222ab.database.windows.net
db.database=myFreeDB
db.username=sc222ab@myfreesqldbserver-sc222ab
db.password=Si_J3tai's--riche
db.certificate=.database.windows.net